"""
RAG ingestion script — run this once (and again whenever new laws are scraped).

Usage:
    cd data
    python ingest.py                    # ingest all categories
    python ingest.py --category ra      # only Republic Acts
    python ingest.py --limit 10         # test run (10 files per category)
    python ingest.py --dry-run          # count chunks without inserting
    python ingest.py --stats            # expected vs DB chunks (how many left)

Prerequisites:
    pip install -r requirements.txt
    Set SUPABASE_DB_URL and GEMINI_API_KEY in backend/.env
    Run `alembic upgrade head` against Supabase at least once so law_chunks exists.

The script is resumable — it skips any chunk IDs already present in the DB.
Embeddings are generated by Gemini text-embedding-004 (768 dimensions, free tier).
"""

from __future__ import annotations

import argparse
import asyncio
import json
import logging
import os
from pathlib import Path

import asyncpg
from dotenv import load_dotenv
from sentence_transformers import SentenceTransformer

# ── env setup ────────────────────────────────────────────────────────────────

_REPO_ROOT = Path(__file__).parent.parent
load_dotenv(_REPO_ROOT / "backend" / ".env")

SUPABASE_DB_URL: str = os.environ["SUPABASE_DB_URL"]

# ── constants ─────────────────────────────────────────────────────────────────

DATA_DIR = Path(__file__).parent

CATEGORIES = {
    "ra": "republic_acts",
    "pd": "presidential_decrees",
    "eo": "executive_orders",
    "bp": "batas_pambansa",
    "ca": "commonwealth_acts",
    "sc": "supreme_court_decisions",
    "ao": "administrative_orders",
}

CHUNK_SIZE = 800    # words per chunk
CHUNK_OVERLAP = 200  # word overlap between consecutive chunks
MIN_CHUNK_WORDS = 60  # discard tiny trailing chunks

# Gemini free-tier embedding: ~1 500 req/min → 0.04 s/req minimum.
# 0.5 s gives comfortable headroom and avoids 429 errors.
EMBED_DELAY_SECONDS = 0.1

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s  %(levelname)-7s  %(message)s",
    datefmt="%H:%M:%S",
)
log = logging.getLogger(__name__)


# ── chunking ──────────────────────────────────────────────────────────────────

def chunk_text(text: str) -> list[str]:
    words = text.split()
    step = CHUNK_SIZE - CHUNK_OVERLAP
    chunks: list[str] = []
    for i in range(0, len(words), step):
        chunk = " ".join(words[i : i + CHUNK_SIZE])
        if len(chunk.split()) >= MIN_CHUNK_WORDS:
            chunks.append(chunk)
    return chunks


def _expected_chunks_for_law(law: dict) -> int:
    full_text = (law.get("full_text") or "").strip()
    if not full_text:
        return 0
    return len(chunk_text(full_text))


def scan_expected_chunks(folder_name: str) -> tuple[int, int, int]:
    """
    Walk *folder_name* under DATA_DIR.

    Returns (json_files_seen, files_with_text, expected_chunk_count).
    """
    cat_dir = DATA_DIR / folder_name
    if not cat_dir.exists():
        return 0, 0, 0
    paths = sorted(p for p in cat_dir.glob("*.json") if p.name != ".gitkeep")
    files_seen = len(paths)
    with_text = 0
    chunks_total = 0
    for path in paths:
        try:
            law = json.loads(path.read_text(encoding="utf-8"))
        except Exception:
            continue
        n = _expected_chunks_for_law(law)
        if n:
            with_text += 1
        chunks_total += n
    return files_seen, with_text, chunks_total


async def print_ingestion_stats(category_keys: list[str]) -> None:
    """Print expected chunk counts from disk vs rows in law_chunks (per category)."""
    conn = await asyncpg.connect(SUPABASE_DB_URL, ssl=False)
    rows = await conn.fetch(
        """
        SELECT category, COUNT(*)::bigint AS n
        FROM law_chunks
        GROUP BY category
        ORDER BY category
        """
    )
    await conn.close()
    db_by_cat: dict[str, int] = {r["category"]: int(r["n"]) for r in rows}

    print("\nIngestion progress (expected from JSON vs rows in DB)\n")
    hdr = f"{'Category':<28} {'Files':>7} {'w/text':>7} {'Expected':>10} {'In DB':>10} {'Left':>10}"
    print(hdr)
    print("-" * len(hdr))

    sum_exp = sum_db = 0
    for key in category_keys:
        folder = CATEGORIES[key]
        files_seen, with_text, expected = scan_expected_chunks(folder)
        in_db = int(db_by_cat.get(folder, 0))
        left = max(0, expected - in_db)
        sum_exp += expected
        sum_db += in_db
        print(
            f"{folder:<28} {files_seen:>7} {with_text:>7} {expected:>10} {in_db:>10} {left:>10}"
        )

    print("-" * len(hdr))
    print(f"{'TOTAL':<28} {'':>7} {'':>7} {sum_exp:>10} {sum_db:>10} {max(0, sum_exp - sum_db):>10}\n")


# ── embedding ─────────────────────────────────────────────────────────────────

def embed_text(model: SentenceTransformer, text: str) -> list[float]:
    return model.encode(text, normalize_embeddings=True).tolist()


# ── ingestion ─────────────────────────────────────────────────────────────────

async def ingest(
    category_keys: list[str],
    limit: int | None,
    dry_run: bool,
    newest: bool = False,
) -> None:
    log.info("Loading embedding model …")
    model = SentenceTransformer("all-mpnet-base-v2")
    log.info("Connecting to database …")
    conn = await asyncpg.connect(SUPABASE_DB_URL, ssl=False)

    existing_ids: set[str] = {
        row["id"] for row in await conn.fetch("SELECT id FROM law_chunks")
    }
    log.info("Found %d existing chunks in DB (will skip these)", len(existing_ids))

    total_inserted = 0
    total_skipped = 0

    for key in category_keys:
        folder_name = CATEGORIES[key]
        cat_dir = DATA_DIR / folder_name

        if not cat_dir.exists():
            log.warning("Folder not found, skipping: %s", cat_dir)
            continue

        json_files = sorted(cat_dir.glob("*.json"))
        if limit:
            if newest:
                # Sort by date_enacted inside the JSON, newest first
                def _get_date(p: Path) -> str:
                    try:
                        return json.loads(p.read_text(encoding="utf-8")).get("date_enacted") or ""
                    except Exception:
                        return ""
                json_files = sorted(json_files, key=_get_date, reverse=True)
            json_files = json_files[:limit]

        log.info("\n%s (%s): %d files to process", folder_name, key, len(json_files))

        for json_file in json_files:
            try:
                with open(json_file, encoding="utf-8") as fh:
                    law = json.load(fh)
            except Exception as exc:
                log.warning("Could not read %s: %s", json_file.name, exc)
                continue

            full_text = (law.get("full_text") or "").strip()
            if not full_text:
                log.debug("No full_text in %s, skipping", json_file.name)
                continue

            slug = json_file.stem
            number = law.get("number", "")
            title = law.get("title", "")

            # Prefix each chunk so the model sees the source in context
            prefix = f"[{number} — {title}]\n"

            chunks = chunk_text(full_text)

            for idx, chunk in enumerate(chunks):
                chunk_id = f"{slug}_chunk_{idx}"

                if chunk_id in existing_ids:
                    total_skipped += 1
                    continue

                text_to_embed = prefix + chunk

                if dry_run:
                    log.info("  [DRY-RUN] would embed %s", chunk_id)
                    total_inserted += 1
                    continue

                try:
                    embedding = embed_text(model, text_to_embed)
                except Exception as exc:
                    log.error("  Embedding failed for %s: %s", chunk_id, exc)
                    continue

                vec_literal = "[" + ",".join(f"{v:.8f}" for v in embedding) + "]"

                await conn.execute(
                    """
                    INSERT INTO law_chunks
                        (id, text, embedding, number, title, category, date_enacted, source_url, chunk_index)
                    VALUES ($1, $2, $3::vector, $4, $5, $6, $7, $8, $9)
                    ON CONFLICT (id) DO NOTHING
                    """,
                    chunk_id,
                    text_to_embed,
                    vec_literal,
                    number,
                    title,
                    law.get("category", folder_name),
                    law.get("date_enacted"),
                    law.get("source_url"),
                    idx,
                )

                existing_ids.add(chunk_id)
                total_inserted += 1

                if total_inserted % 50 == 0:
                    log.info("  … %d chunks inserted so far", total_inserted)


    await conn.close()

    log.info(
        "\nDone. Inserted: %d  |  Skipped (already in DB): %d",
        total_inserted,
        total_skipped,
    )


# ── CLI ───────────────────────────────────────────────────────────────────────

def main() -> None:
    parser = argparse.ArgumentParser(description="Ingest Philippine law JSON files into pgvector (Supabase)")
    parser.add_argument(
        "--category",
        choices=list(CATEGORIES.keys()),
        nargs="+",
        default=list(CATEGORIES.keys()),
        help="Which categories to ingest (default: all). E.g. --category ra eo",
    )
    parser.add_argument(
        "--limit",
        type=int,
        default=None,
        help="Max files per category (useful for test runs, e.g. --limit 5)",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Count chunks without calling the embedding API or writing to DB",
    )
    parser.add_argument(
        "--newest",
        action="store_true",
        help="When used with --limit, pick the most recently enacted files instead of alphabetical",
    )
    parser.add_argument(
        "--stats",
        action="store_true",
        help="Scan JSON folders and compare expected chunk counts to DB (no model, no writes)",
    )
    args = parser.parse_args()

    if args.stats:
        asyncio.run(print_ingestion_stats(args.category))
        return

    asyncio.run(ingest(args.category, args.limit, args.dry_run, args.newest))


if __name__ == "__main__":
    main()
