"""
RAG ingestion script — run this once (and again whenever new laws are scraped).

Usage:
    cd data
    python ingest.py                    # ingest all categories
    python ingest.py --category ra      # only Republic Acts
    python ingest.py --category sec_mc  # only SEC Memorandum Circulars
    python ingest.py --category irr_doh # only DOH IRRs
    python ingest.py --limit 10         # test run (10 files per category)
    python ingest.py --dry-run          # count chunks without inserting

Prerequisites:
    pip install -r requirements.txt
    Set SUPABASE_DB_URL and GEMINI_API_KEY in backend/.env
    Run `alembic upgrade head` against Supabase at least once so law_chunks exists.

The script is resumable — it skips any chunk IDs already present in the DB.
Embeddings are generated by Gemini gemini-embedding-001 (768 dimensions).
"""

from __future__ import annotations

import argparse
import asyncio
import json
import logging
import os
import time
from pathlib import Path

import asyncpg
from dotenv import load_dotenv
from google.genai import Client, types

# ── env setup ─────────────────────────────────────────────────────────────────

_REPO_ROOT = Path(__file__).parent.parent
load_dotenv(_REPO_ROOT / "backend" / ".env")

SUPABASE_DB_URL: str = os.environ["SUPABASE_DB_URL"]
GEMINI_API_KEY: str = os.environ["GEMINI_API_KEY"]

# ── constants ─────────────────────────────────────────────────────────────────

DATA_DIR = Path(__file__).parent

# ── Category registry ─────────────────────────────────────────────────────────
# Keys are the short CLI aliases used with --category.
# Values are the folder names under DATA_DIR.
# When adding a new scraper, register its output folders here.

CATEGORIES: dict[str, str] = {
    # ── Original ──────────────────────────────────────────────────────────────
    "ra":  "republic_acts",
    "pd":  "presidential_decrees",
    "eo":  "executive_orders",
    "bp":  "batas_pambansa",
    "ca":  "commonwealth_acts",
    "sc":  "supreme_court_decisions",
    "ao":  "administrative_orders",

    # ── SEC ───────────────────────────────────────────────────────────────────
    "sec_mc":       "sec_memorandum_circulars",
    "sec_opinions": "sec_opinions",
    "sec_notices":  "sec_notices",

    # ── BIR ───────────────────────────────────────────────────────────────────
    "bir_rr":  "bir_revenue_regulations",
    "bir_rmo": "bir_revenue_memorandum_orders",
    "bir_rmc": "bir_revenue_memorandum_circulars",
    "bir_rb":  "bir_revenue_bulletins",

    # ── DOH ───────────────────────────────────────────────────────────────────
    "doh_ao": "doh_administrative_orders",
    "doh_dc": "doh_department_circulars",
    "doh_dm": "doh_department_memoranda",

    # ── PhilHealth ────────────────────────────────────────────────────────────
    "ph_pc": "philhealth_circulars",
    "ph_br": "philhealth_board_resolutions",

    # ── IRR ───────────────────────────────────────────────────────────────────
    "irr_exec": "irr_executive",
    "irr_jud":  "irr_judiciary",
    "irr_leg":  "irr_legislative",
    "irr_sec":  "irr_sec",
    "irr_bir":  "irr_bir",
    "irr_doh":  "irr_doh",
    "irr_ph":   "irr_philhealth",
}

# ── Chunking settings ─────────────────────────────────────────────────────────
CHUNK_SIZE     = 800   # words per chunk
CHUNK_OVERLAP  = 200   # word overlap between consecutive chunks
MIN_CHUNK_WORDS = 60   # discard tiny trailing chunks

# Gemini free-tier embedding: ~1 500 req/min → 0.04 s/req minimum.
# 0.5 s gives comfortable headroom and avoids 429 errors.
EMBED_DELAY_SECONDS = 0.5

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s  %(levelname)-7s  %(message)s",
    datefmt="%H:%M:%S",
)
log = logging.getLogger(__name__)


# ── Chunking ──────────────────────────────────────────────────────────────────

def chunk_text(text: str) -> list[str]:
    words = text.split()
    step = CHUNK_SIZE - CHUNK_OVERLAP
    chunks: list[str] = []
    for i in range(0, len(words), step):
        chunk = " ".join(words[i : i + CHUNK_SIZE])
        if len(chunk.split()) >= MIN_CHUNK_WORDS:
            chunks.append(chunk)
    return chunks


# ── Embedding ─────────────────────────────────────────────────────────────────

async def embed_text(client: Client, text: str) -> list[float]:
    result = await client.aio.models.embed_content(
        model="models/gemini-embedding-001",
        contents=text,
    )
    return list(result.embeddings[0].values)


# ── Ingestion ─────────────────────────────────────────────────────────────────

async def ingest(
    category_keys: list[str],
    limit: int | None,
    dry_run: bool,
) -> None:
    log.info("Connecting to Supabase …")
    conn = await asyncpg.connect(SUPABASE_DB_URL, ssl="require")
    gemini = Client(api_key=GEMINI_API_KEY)

    existing_ids: set[str] = {
        row["id"] for row in await conn.fetch("SELECT id FROM law_chunks")
    }
    log.info("Found %d existing chunks in DB (will skip these)", len(existing_ids))

    total_inserted = 0
    total_skipped  = 0

    for key in category_keys:
        folder_name = CATEGORIES[key]
        cat_dir = DATA_DIR / folder_name

        if not cat_dir.exists():
            log.warning("Folder not found, skipping: %s", cat_dir)
            continue

        json_files = sorted(cat_dir.glob("*.json"))
        if limit:
            json_files = json_files[:limit]

        log.info("\n%s (%s): %d files to process", folder_name, key, len(json_files))

        for json_file in json_files:
            try:
                with open(json_file, encoding="utf-8") as fh:
                    law = json.load(fh)
            except Exception as exc:
                log.warning("Could not read %s: %s", json_file.name, exc)
                continue

            full_text = (law.get("full_text") or "").strip()
            # Skip PDF-placeholder records (philhealth --include-pdf-meta)
            if not full_text or full_text.startswith("[PDF]"):
                log.debug("No usable full_text in %s, skipping", json_file.name)
                continue

            slug   = json_file.stem
            number = law.get("number", "")
            title  = law.get("title", "")

            # Prefix each chunk so the model sees the source in context
            prefix = f"[{number} — {title}]\n"
            chunks = chunk_text(full_text)

            for idx, chunk in enumerate(chunks):
                chunk_id = f"{slug}_chunk_{idx}"

                if chunk_id in existing_ids:
                    total_skipped += 1
                    continue

                text_to_embed = prefix + chunk

                if dry_run:
                    log.info("  [DRY-RUN] would embed %s", chunk_id)
                    total_inserted += 1
                    continue

                try:
                    embedding = await embed_text(gemini, text_to_embed)
                except Exception as exc:
                    log.error("  Embedding failed for %s: %s", chunk_id, exc)
                    continue

                vec_literal = "[" + ",".join(f"{v:.8f}" for v in embedding) + "]"

                await conn.execute(
                    """
                    INSERT INTO law_chunks
                        (id, text, embedding, number, title,
                         category, date_enacted, source_url, chunk_index)
                    VALUES ($1, $2, $3::vector, $4, $5, $6, $7, $8, $9)
                    ON CONFLICT (id) DO NOTHING
                    """,
                    chunk_id,
                    text_to_embed,
                    vec_literal,
                    number,
                    title,
                    law.get("category", folder_name),
                    law.get("date_enacted"),
                    law.get("source_url"),
                    idx,
                )

                existing_ids.add(chunk_id)
                total_inserted += 1

                if total_inserted % 50 == 0:
                    log.info("  … %d chunks inserted so far", total_inserted)

                time.sleep(EMBED_DELAY_SECONDS)

    await conn.close()

    log.info(
        "\nDone. Inserted: %d  |  Skipped (already in DB): %d",
        total_inserted,
        total_skipped,
    )


# ── CLI ───────────────────────────────────────────────────────────────────────

def main() -> None:
    parser = argparse.ArgumentParser(
        description="Ingest Philippine law JSON files into pgvector (Supabase)"
    )
    parser.add_argument(
        "--category",
        choices=list(CATEGORIES.keys()),
        nargs="+",
        default=list(CATEGORIES.keys()),
        help=(
            "Which categories to ingest (default: all). "
            "E.g. --category sec_mc bir_rr irr_doh"
        ),
    )
    parser.add_argument(
        "--limit",
        type=int,
        default=None,
        help="Max files per category (useful for test runs, e.g. --limit 5)",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Count chunks without calling the embedding API or writing to DB",
    )
    args = parser.parse_args()

    asyncio.run(ingest(args.category, args.limit, args.dry_run))


if __name__ == "__main__":
    main()